version: '3.8'
services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    networks:
      - backend

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:
    name: backend
    driver: bridge
